const NS_PRODUCT_DETAIL = 'productDetail';
const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL';

export default {
  NS_PRODUCT_DETAIL,
  GET_PRODUCT_DETAIL,
  SET_PRODUCT_DETAIL,
};
