const NS_PRODUCT = 'product';

const GET_LIST_CATEGORIES = 'GET_LIST_CATEGORIES';
const SET_LIST_CATEGORIES = 'SET_LIST_CATEGORIES';
const GET_LIST_PRODUCT = 'GET_LIST_PRODUCT';
const SET_LIST_PRODUCT = 'SET_LIST_PRODUCT';

export default {
  NS_PRODUCT,
  GET_LIST_CATEGORIES,
  SET_LIST_CATEGORIES,
  GET_LIST_PRODUCT,
  SET_LIST_PRODUCT,
};
